### PR TITLE
Use the parsed request body rather than ctx.body

### PR DESCRIPTION
**Pull request by jmurzy**
The Koa adapter is incorrectly using the response body (ctx.body) instead of the request body (ctx.request.body).

### CODE REVIEW

**Comment by enisdenjo** [comment]
Thanks for this PR! Can you please rebase and fix the failing lint+type checks?

**Comment by jmurzy** [comment]
@enisdenjo it should be fixed now. Thanks!

**Comment by enisdenjo** [comment]
Thank you @jmurzy, great work!

**Pull request merged**
