### PR TITLE
Fix: jsonErrorReplacer to use explicit Error type

### PR DESCRIPTION
**Pull request by h3ssan**
## Description

This PR refactors the jsonErrorReplacer function to use explicit Error casting, improving type safety and preventing potential errors.

## Changes

In the `src/handler.ts` file, the `jsonErrorReplacer` function contains an argument `val` with a type of `any`. However, the function also includes a type check `val instanceof Error`, which allows for a safe cast to the Error type. To leverage this type information, we can introduce a type cast using the `as` keyword, assigning the casted value to a new variable error. This refinement enables the TypeScript compiler to accurately infer the type of error and eliminates any potential type errors.

### CODE REVIEW

**Review by enisdenjo — APPROVED** [review]
This looks good! Am wondering why TS didnt infer this type cast due to the narrowing. 🤔

**Comment by h3ssan** [comment]
> This looks good! Am wondering why TS didnt infer this type cast due to the narrowing. 🤔

Thank you! Yes, sometimes you can't depend on a machine, lol

**Comment by benjie** [comment]
Maybe if `val` was `unknown` rather than `any` it would work?

**Pull request merged**
