### PR TITLE
feat(audits/server): Test that `null` is allowed for body parameters

### LINKED ISSUE #26: Should have audits for accepting `null`s
The spec has a paragraph that states:

> Note: Specifying `null` in JSON (or equivalent values in other formats) as values for optional request parameters is equivalent to not specifying them at all.

The audit suite should test this explicitly.

(I was inspired by the audit suite to be stricter about banning things like `variables: 0` and got carried away and also banned `variables: null`. So the suite should prevent this over-fitting.)

### PR DESCRIPTION
**Pull request by glasser**
As per spec:

> Note: Specifying `null` in JSON (or equivalent values in other
> formats) as values for optional request parameters is equivalent to
> not specifying them at all.

Fixes #26.

### CODE REVIEW

**Review by enisdenjo — APPROVED** [review]
Thank you!

**Comment by glasser** [comment]
@mcollina FYI this removes mercurius from the passing list because it chokes on `extensions: null`; pretty sure that should be a quick fix for you?

(Technically it should remove `apollo-server` too because the latest version doesn't pass even if the slightly old version being tested does, but I'll fix that today.)

**Comment by benjie** [comment]
Are we certain that this is a requirement we want in the spec? I'm definitely open to removing it if it's causing compatibility issues, I'm not even sure that `{query: "{__typename}", extensions: null}` _should_ constitute a valid request...

**Comment by glasser** [comment]
FWIW it does appear that some clients like https://github.com/graphql-rust/graphql-client send `variables: null` (and `operationName: null` seems quite common) so it seems like a good requirement. I guess `extensions` is sketchier but seems reasonable by analogy (and `extensions` being spec-defined is pretty new anyway...)

**Comment by benjie** [comment]
Ah yes, we definitely want existing clients to continue to work, thanks for the reference @glasser. In which case, this rule should increase interoperability and we'll maintain it 👍

**Pull request merged**
